### ISSUE TITLE
File conflict between aliyun-python-sdk-core and aliyun-python-sdk-core-v3

### ISSUE THREAD

**Issue by glaubitz** [aliyun/aliyun-openapi-python-sdk#356]
I'm currently packaging the Python Alibaba SDK for openSUSE/SLE and I have run into some issues, in particular with the packages ```aliyun-python-sdk-core``` and ```aliyun-python-sdk-core-v3```.

Both packages are trying to install files below ```/usr/lib/$PYTHONVER/site-packages/aliyunsdkcore/``` (see RPM output below):

```
File /usr/lib/python3.8/site-packages/aliyunsdkcore/__init__.py
  from install of
     python3-aliyun-python-sdk-core-2.13.16-2.1.noarch (Branch project for package python-aliyun-python-sdk-aas (openSUSE_Tumbleweed))
  conflicts with file from install of
     python3-aliyun-python-sdk-core-v3-2.13.11-2.1.noarch (Branch project for package python-aliyun-python-sdk-aas (openSUSE_Tumbleweed))

File /usr/lib/python3.8/site-packages/aliyunsdkcore/__pycache__/__init__.cpython-38.opt-1.pyc
  from install of
     python3-aliyun-python-sdk-core-2.13.16-2.1.noarch (Branch project for package python-aliyun-python-sdk-aas (openSUSE_Tumbleweed))
  conflicts with file from install of
     python3-aliyun-python-sdk-core-v3-2.13.11-2.1.noarch (Branch project for package python-aliyun-python-sdk-aas (openSUSE_Tumbleweed))

File /usr/lib/python3.8/site-packages/aliyunsdkcore/__pycache__/__init__.cpython-38.pyc
  from install of
     python3-aliyun-python-sdk-core-2.13.16-2.1.noarch (Branch project for package python-aliyun-python-sdk-aas (openSUSE_Tumbleweed))
  conflicts with file from install of
     python3-aliyun-python-sdk-core-v3-2.13.11-2.1.noarch (Branch project for package python-aliyun-python-sdk-aas (openSUSE_Tumbleweed))

File /usr/lib/python3.8/site-packages/aliyunsdkcore/__pycache__/client.cpython-38.opt-1.pyc
  from install of
     python3-aliyun-python-sdk-core-2.13.16-2.1.noarch (Branch project for package python-aliyun-python-sdk-aas (openSUSE_Tumbleweed))
  conflicts with file from install of
     python3-aliyun-python-sdk-core-v3-2.13.11-2.1.noarch (Branch project for package python-aliyun-python-sdk-aas (openSUSE_Tumbleweed))

File /usr/lib/python3.8/site-packages/aliyunsdkcore/__pycache__/client.cpython-38.pyc
  from install of
     python3-aliyun-python-sdk-core-2.13.16-2.1.noarch (Branch project for package python-aliyun-python-sdk-aas (openSUSE_Tumbleweed))
  conflicts with file from install of
     python3-aliyun-python-sdk-core-v3-2.13.11-2.1.noarch (Branch project for package python-aliyun-python-sdk-aas (openSUSE_Tumbleweed))

File /usr/lib/python3.8/site-packages/aliyunsdkcore/__pycache__/request.cpython-38.opt-1.pyc
  from install of
     python3-aliyun-python-sdk-core-2.13.16-2.1.noarch (Branch project for package python-aliyun-python-sdk-aas (openSUSE_Tumbleweed))
  conflicts with file from install of
     python3-aliyun-python-sdk-core-v3-2.13.11-2.1.noarch (Branch project for package python-aliyun-python-sdk-aas (openSUSE_Tumbleweed))

File /usr/lib/python3.8/site-packages/aliyunsdkcore/__pycache__/request.cpython-38.pyc
  from install of
     python3-aliyun-python-sdk-core-2.13.16-2.1.noarch (Branch project for package python-aliyun-python-sdk-aas (openSUSE_Tumbleweed))
  conflicts with file from install of
     python3-aliyun-python-sdk-core-v3-2.13.11-2.1.noarch (Branch project for package python-aliyun-python-sdk-aas (openSUSE_Tumbleweed))

File /usr/lib/python3.8/site-packages/aliyunsdkcore/client.py
  from install of
     python3-aliyun-python-sdk-core-2.13.16-2.1.noarch (Branch project for package python-aliyun-python-sdk-aas (openSUSE_Tumbleweed))
  conflicts with file from install of
     python3-aliyun-python-sdk-core-v3-2.13.11-2.1.noarch (Branch project for package python-aliyun-python-sdk-aas (openSUSE_Tumbleweed))

File /usr/lib/python3.8/site-packages/aliyunsdkcore/data/endpoints.json
  from install of
     python3-aliyun-python-sdk-core-2.13.16-2.1.noarch (Branch project for package python-aliyun-python-sdk-aas (openSUSE_Tumbleweed))
  conflicts with file from install of
     python3-aliyun-python-sdk-core-v3-2.13.11-2.1.noarch (Branch project for package python-aliyun-python-sdk-aas (openSUSE_Tumbleweed))

File /usr/lib/python3.8/site-packages/aliyunsdkcore/request.py
  from install of
     python3-aliyun-python-sdk-core-2.13.16-2.1.noarch (Branch project for package python-aliyun-python-sdk-aas (openSUSE_Tumbleweed))
  conflicts with file from install of
     python3-aliyun-python-sdk-core-v3-2.13.11-2.1.noarch (Branch project for package python-aliyun-python-sdk-aas (openSUSE_Tumbleweed))

File /usr/lib/python3.8/site-packages/aliyunsdkcore/utils/__pycache__/parameter_helper.cpython-38.opt-1.pyc
  from install of
     python3-aliyun-python-sdk-core-2.13.16-2.1.noarch (Branch project for package python-aliyun-python-sdk-aas (openSUSE_Tumbleweed))
  conflicts with file from install of
     python3-aliyun-python-sdk-core-v3-2.13.11-2.1.noarch (Branch project for package python-aliyun-python-sdk-aas (openSUSE_Tumbleweed))

File /usr/lib/python3.8/site-packages/aliyunsdkcore/utils/__pycache__/parameter_helper.cpython-38.pyc
  from install of
     python3-aliyun-python-sdk-core-2.13.16-2.1.noarch (Branch project for package python-aliyun-python-sdk-aas (openSUSE_Tumbleweed))
  conflicts with file from install of
     python3-aliyun-python-sdk-core-v3-2.13.11-2.1.noarch (Branch project for package python-aliyun-python-sdk-aas (openSUSE_Tumbleweed))

File /usr/lib/python3.8/site-packages/aliyunsdkcore/utils/parameter_helper.py
  from install of
     python3-aliyun-python-sdk-core-2.13.16-2.1.noarch (Branch project for package python-aliyun-python-sdk-aas (openSUSE_Tumbleweed))
  conflicts with file from install of
     python3-aliyun-python-sdk-core-v3-2.13.11-2.1.noarch (Branch project for package python-aliyun-python-sdk-aas (openSUSE_Tumbleweed))
```

If I understand correctly, the package ```aliyun-python-sdk-core-v3``` is required for Python 3. However, some packages of the SDK have a strict dependency on ```aliyun-python-sdk-core```, while others depend on ```aliyun-python-sdk-core-v3``` in their ```setup.py```.

For example, ```aliyun-python-sdk-aas``` depends on ```aliyun-python-sdk-core``` while ```python-aliyun-python-sdk-arms4finance``` depends on ```aliyun-python-sdk-core-v3```.

As a result,  ```aliyun-python-sdk-aas``` and ```python-aliyun-python-sdk-arms4finance``` cannot be installed at the same time.

A similar file conflict exists between ```aliyun-python-sdk-dysmsapi``` and ```aliyun-python-sdk-dybaseapi``` for which I will file a separate bug report.

**Comment by JacksonTian** [comment]
Hi @glaubitz . Sorry for this question.

For historical reasons, in the past we provided `core` and `core-v3` for Python 2/3. In last year we use six to make the `core` can be compatible with python 2/3 both. So now the  `core` and `core-v3` are the same. 

We will re-publish the packages that depend on v3 ASAP.

**Comment by glaubitz** [comment]
@JacksonTian Thanks! Just updating the packages in PyPi should fix all the issues I have run into since they are fixed in git :).

**Comment by JacksonTian** [comment]
@glaubitz we have released new packages. I close the issue. If any questions, feel free to re-open it.

**Comment by glaubitz** [comment]
@JacksonTian 

The following packages have not been updated on PyPi yet:

- aliyun-python-sdk-arms4finance
- aliyun-python-sdk-batchcompute
- aliyun-python-sdk-bsn
- aliyun-python-sdk-cloudmarketing
- aliyun-python-sdk-dysmsapi
- aliyun-python-sdk-jaq
- aliyun-python-sdk-ossadmin

Could you update those as well so that they don't pull in the old version of the core package anymore?

**Comment by 824750130** [comment]
Thanks for your feedback, we will release the latest version immediately.

**Comment by glaubitz** [comment]
Thanks.

It looks like you missed these two packages, their latest releases are still from 2017:

- https://pypi.org/project/aliyun-python-sdk-batchcompute/#history
- https://pypi.org/project/aliyun-python-sdk-bsn/#history

Could you update these as well?

**Comment by glaubitz** [comment]
Hello! Any updates on the two outdated packages aliyun-python-sdk-batch and aliyun-python-sdk-bsn?
